apiVersion: v1
kind: Service
metadata:
  name: api-sample-service
  labels:
    app: api-sample
spec:
  selector:
    app: api-sample
  ports:
    - port: 38382
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sample-ac
  labels:
    app: api-sample